theme: jekyll-theme-minimal
title: EasyMedics for Laboratory
description: A medical record management and billing solution, ideal for managing diagnostic centers and laboratory workflows!
show_downloads: true
github:
  zip_url: setup.exe
  tar_url: EasyMedics.application


